name: Validate, Release, and Publish Features

on:
  push:
    branches:
      - main
    paths:
      - 'features/**'
      - '.github/workflows/**'
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-features:
    name: Validate feature.json files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate feature.json syntax
        run: |
          echo "Validating all feature.json files..."
          find features -name feature.json | while read file; do
            echo "Checking $file"
            jq empty "$file"
          done

  release:
    name: Release Please (manage releases)
    runs-on: ubuntu-latest
    needs: validate-features
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Release Please
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
          token: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish Features (after release)
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate all feature.json files
        run: |
          echo "Re-validating feature.json files..."
          find features -name feature.json | while read file; do
            echo "Checking $file"
            jq empty "$file"
          done

      - name: Package features into zip files
        run: |
          echo "Packaging features..."
          mkdir -p artifacts
          find features -maxdepth 1 -mindepth 1 -type d | while read feature_dir; do
            feature_name=$(basename "$feature_dir")
            echo "Zipping $feature_name..."
            zip -r "artifacts/${feature_name}.zip" "$feature_dir"
          done

      - name: Upload feature artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
