name: Validate Features in Clean Containers

on:
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/test-features.yml'
      - '.github/scripts/test-features.sh'
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/test-features.yml'
      - '.github/scripts/test-features.sh'

permissions:
  contents: read

jobs:
  test-features:
    name: Test Devcontainer Features
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (for Dev Container CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dev Container CLI
        run: npm install -g @devcontainers/cli

      - name: Run feature tests
        run: bash .github/scripts/test-features.sh